//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.item_stats = new HashSet<ItemStats>();
        }
    
        public int id { get; set; }
        public string maple_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int category { get; set; }
        public string image { get; set; }
        public int min_str { get; set; }
        public int max_str { get; set; }
        public int min_dex { get; set; }
        public int max_dex { get; set; }
        public int min_int { get; set; }
        public int max_int { get; set; }
        public int min_luk { get; set; }
        public int max_luk { get; set; }
        public int min_watt { get; set; }
        public int max_watt { get; set; }
        public int min_matt { get; set; }
        public int max_matt { get; set; }
        public int min_hp { get; set; }
        public int max_hp { get; set; }
        public int min_acc { get; set; }
        public int max_acc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStats> item_stats { get; set; }
    }
}
