//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemStats()
        {
            this.price = new HashSet<Price>();
        }
    
        public int id { get; set; }
        public int item_id { get; set; }
        public int stats_id { get; set; }
    
        public virtual Item item { get; set; }
        public virtual Stats stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> price { get; set; }
    }
}
