//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapleMarketEntities : DbContext
    {
        public MapleMarketEntities(string connStr)
            : base(connStr)
        {
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemStats> ItemStats { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<PriceEvent> PriceEvent { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
    }
}
