//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceEvent
    {
        public int id { get; set; }
        public int price_id { get; set; }
        public int event_id { get; set; }
    
        public virtual Event @event { get; set; }
        public virtual Price price { get; set; }
    }
}
