//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stats()
        {
            this.item_stats = new HashSet<ItemStats>();
        }
    
        public int id { get; set; }
        public int str { get; set; }
        public int dex { get; set; }
        public int @int { get; set; }
        public int luk { get; set; }
        public int w_att { get; set; }
        public int m_att { get; set; }
        public int slots { get; set; }
        public int hp { get; set; }
        public int acc { get; set; }
        public string percent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStats> item_stats { get; set; }
    }
}
